# Generated by Django 5.2 on 2025-05-09 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_users_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='dep_name',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='doc_image',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='doc_name',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='doc_spec',
        ),
    ]
