# Generated by Django 5.2 on 2025-05-09 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_doctors_dep_name_remove_doctors_doc_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='doc_name',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Doctors',
        ),
    ]
