# Generated by Django 5.2 on 2025-05-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contact_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='doc_name',
        ),
    ]
