# Generated by Django 5.2 on 2025-05-09 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_doctors_doc_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='doc_name',
            new_name='doc_id',
        ),
    ]
