# Generated by Django 5.2 on 2025-05-09 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_doc_name_booking_doc_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.CharField(max_length=255)),
                ('prescribed_on', models.DateTimeField(auto_now=True)),
                ('p_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.booking')),
                ('prescribed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.doctors')),
            ],
        ),
    ]
